### ISSUE TITLE
Stops after swipe/killing the app

### ISSUE THREAD

**Issue by deckameron** [benbahrenburg/Ti.GeoVisits#2]
Hi @benbahrenburg 
Thank you for creating this module!
I have implemented it using your example "app.js" and it works just fine while the app is opened. But, I closed the app using the swipe up gesture and it is not adding the lat lon to listview anymore. I have read the Apple documentation and it says it should be working. That the event would raise the app make it work again.
Do I have to do anything else to make it work when app is closed?

My best,

**Comment by benbahrenburg** [comment]
You would want to use Significant Location Change in the Ti SDK for this as it will (should) awake up your app.  Depending on your pooling frequency you might find sending a silent push notification another option.

**Comment by deckameron** [comment]
Thank you for your fast reponse!
So I would just add this line to your app.js code? That's it?
`Titanium.Geolocation.trackSignificantLocationChange = true`

**Comment by benbahrenburg** [comment]
You would need to use the core Ti.Geolocation method.

I can't remember the syntax off the top of my head, but the docs should have a good example http://docs.appcelerator.com/platform/latest/#!/api/Titanium.Geolocation

**Comment by deckameron** [comment]
I am sorry but I understood you wrong.
So what you saying is that I can not use your module but use the Ti.Geolocation instead. Right?

**Comment by benbahrenburg** [comment]
Correct. The API that this module uses, CLVisits doesn't (to my knowledge) "wake-up" your app if it has been killed by the OS or user. 

If you are looking for that functionality, you would want to look at putting together a combination of the Significant Location Change event (core Ti SDK) and using silent push notifications.

**Comment by deckameron** [comment]
I see! Just like you did on your Ti.Geo.Background module.
I am trying to create a geofence behaviour on my App. That is why I am so worried about the background services keep working after the app gets killed.
Thank you very much!

**Comment by benbahrenburg** [comment]
There are a few geofencing modules out there.  I believe this should also wake-up your app if killed.

http://docs.appcelerator.com/platform/latest/#!/api/Modules.Geofence
https://gist.github.com/stevenou/1830512

**Comment by deckameron** [comment]
I was very happy until I saw this:
**This feature requires a Pro or Enterprise subscription!**

I am testing your Ti.Geo.Background module right now. It seems to be working fine when app is killed.
I added a localNotification code like you suggested, but It is failing to display the notification sometimes. But I can see the app being called on the xcode device logs.

**Comment by benbahrenburg** [comment]
Another one to explore http://gitt.io/component/ci.geofencing

**Comment by deckameron** [comment]
Thank you! I will give it a try!

About CLVisits:
I was [reading about](http://nshipster.com/core-location-in-ios-8/) it and just found out that it wakes up the app in background. :)
